{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "craftista.fullname" . }}-postgresql-credentials
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  username: {{ "devops" | b64enc | quote }}
  password: {{ "devops" | b64enc | quote }}
{{- end }}