name: Voting CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'voting/**'
      - '.github/workflows/voting.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'voting/**'
      - '.github/workflows/voting.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/craftista-voting

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./voting
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run tests
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/voting \
          maven:3.9.5-eclipse-temurin-17 \
          mvn test
    
    - name: Run checkstyle
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace/voting \
          maven:3.9.5-eclipse-temurin-17 \
          mvn checkstyle:check || true

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./voting
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64